/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteapp;

import restauranteapp.TelaCadastroFuncionario;
import javax.swing.*;
import restauranteapp.TelaCadastroClientes;
/**
 *
 * @author fernando
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

         public TelaMenuPrincipal() {
        initComponents();
        
        // Configurações da janela
        setTitle("Menu Principal");
        setSize(400, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centraliza a janela
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCadastroFuncionarios = new javax.swing.JButton();
        btnCadastroClientes = new javax.swing.JButton();
        btnCadastroPratos = new javax.swing.JButton();
        btnRegistroPedidos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Restaurante Sabor e Arte");

        btnCadastroFuncionarios.setText("Cadastro de Funcionários ");
        btnCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFuncionariosActionPerformed(evt);
            }
        });

        btnCadastroClientes.setText("Cadastro de Clientes ");
        btnCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClientesActionPerformed(evt);
            }
        });

        btnCadastroPratos.setText("Cadastro de Pratos");
        btnCadastroPratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPratosActionPerformed(evt);
            }
        });

        btnRegistroPedidos.setText("Registro de Pedidos");
        btnRegistroPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPedidosActionPerformed(evt);
            }
        });

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistroPedidos)
                            .addComponent(btnCadastroFuncionarios)
                            .addComponent(lblTitulo)
                            .addComponent(btnCadastroClientes)
                            .addComponent(btnCadastroPratos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSair)))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroClientes)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroPratos)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroPedidos)
                .addGap(90, 90, 90)
                .addComponent(btnSair)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClientesActionPerformed
       TelaCadastroClientes tela = new TelaCadastroClientes();
    tela.setVisible(true);
    }//GEN-LAST:event_btnCadastroClientesActionPerformed

    private void btnCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFuncionariosActionPerformed
    TelaCadastroFuncionario telaCadastro = new TelaCadastroFuncionario();
    telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastroFuncionariosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here: 
              System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastroPratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPratosActionPerformed
    TelaCadastroPrato telaPrato = new TelaCadastroPrato();
telaPrato.setVisible(true);
    }//GEN-LAST:event_btnCadastroPratosActionPerformed

    private void btnRegistroPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPedidosActionPerformed
        TelaRegistroPedido telaRegistro = new TelaRegistroPedido();
telaRegistro.setVisible(true);
    }//GEN-LAST:event_btnRegistroPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroClientes;
    private javax.swing.JButton btnCadastroFuncionarios;
    private javax.swing.JButton btnCadastroPratos;
    private javax.swing.JButton btnRegistroPedidos;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
